# NIFTY100 Financial Analytics

## Sprint 2 – Day 10

# Recommendation Engine

This notebook generates investment recommendations based on:

- Performance Score
- Growth Score
- Risk Score
- Overall Company Score
- Investment Category

The output is a recommendation dataset that classifies companies into:

- BUY
- HOLD
- SELL

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
ROOT = Path("../")

OUTPUT = ROOT / "outputs"

analytics = pd.read_csv(
    OUTPUT / "final_analytics.csv"
)

analytics.head()

,rank,company_id,Performance_Score,growth_score,risk_score,overall_score,value_at_risk,investment_category
0,1,COALINDIA,14427.668,-3.792529,10803.945328,3068.753483,-4.77,High Risk
1,2,BAJFINANCE,6073.536,7.913249,7672.010722,514.181356,6.61,High Risk
2,3,HINDUNILVR,4418.928,2.342267,5183.738846,472.456282,0.96,High Risk
3,4,BEL,1906.620,8.160364,2098.775705,240.810201,3.80,Value
4,5,HEROMOTOCO,1635.056,6.623681,1747.970814,219.347985,-9.22,Value

In [3]:
print(analytics.shape)

analytics.info()

(100, 8)
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rank                 100 non-null    int64
 1   company_id           100 non-null    str
 2   Performance_Score    100 non-null    float64
 3   growth_score         100 non-null    float64
 4   risk_score           100 non-null    float64
 5   overall_score        100 non-null    float64
 6   value_at_risk        100 non-null    float64
 7   investment_category  100 non-null    str
dtypes: float64(5), int64(1), str(2)
memory usage: 6.4 KB

## Investment Recommendation Logic

Recommendations are generated using:

- Overall Score
- Risk Score
- Investment Category

Rules:

BUY  → High Overall Score + Low Risk

HOLD → Medium Overall Score

SELL → High Risk OR Poor Overall Score

In [4]:
def recommend(row):

    if (
        row["overall_score"] >= 100
        and row["risk_score"] < 2000
    ):
        return "BUY"

    elif (
        row["overall_score"] >= 40
        and row["risk_score"] < 5000
    ):
        return "HOLD"

    else:
        return "SELL"


analytics["recommendation"] = analytics.apply(
    recommend,
    axis=1
)

analytics.head()

,rank,company_id,Performance_Score,growth_score,risk_score,overall_score,value_at_risk,investment_category,recommendation
0,1,COALINDIA,14427.668,-3.792529,10803.945328,3068.753483,-4.77,High Risk,SELL
1,2,BAJFINANCE,6073.536,7.913249,7672.010722,514.181356,6.61,High Risk,SELL
2,3,HINDUNILVR,4418.928,2.342267,5183.738846,472.456282,0.96,High Risk,SELL
3,4,BEL,1906.620,8.160364,2098.775705,240.810201,3.80,Value,HOLD
4,5,HEROMOTOCO,1635.056,6.623681,1747.970814,219.347985,-9.22,Value,BUY

In [5]:
analytics["recommendation"].value_counts()

recommendation
SELL    96
HOLD     3
BUY      1
Name: count, dtype: int64

In [6]:
buy = analytics[
    analytics["recommendation"] == "BUY"
].copy()

buy.head()

,rank,company_id,Performance_Score,growth_score,risk_score,overall_score,value_at_risk,investment_category,recommendation
4,5,HEROMOTOCO,1635.056,6.623681,1747.970814,219.347985,-9.22,Value,BUY

In [7]:
buy.to_csv(
    OUTPUT / "buy_recommendations.csv",
    index=False
)

print("BUY recommendations saved!")

BUY recommendations saved!

In [8]:
hold = analytics[
    analytics["recommendation"] == "HOLD"
].copy()

hold.head()

,rank,company_id,Performance_Score,growth_score,risk_score,overall_score,value_at_risk,investment_category,recommendation
3,4,BEL,1906.620,8.160364,2098.775705,240.810201,3.80,Value,HOLD
5,6,CIPLA,1908.820,9.894390,2345.399098,180.641262,4.47,Value,HOLD
6,7,HAL,1570.432,5.636570,2261.626427,64.738993,2.89,Value,HOLD

In [9]:
hold.to_csv(
    OUTPUT / "hold_recommendations.csv",
    index=False
)

print("HOLD recommendations saved!")

HOLD recommendations saved!

In [10]:
sell = analytics[
    analytics["recommendation"] == "SELL"
].copy()

sell.head()

,rank,company_id,Performance_Score,growth_score,risk_score,overall_score,value_at_risk,investment_category,recommendation
0,1,COALINDIA,14427.668,-3.792529,10803.945328,3068.753483,-4.77,High Risk,SELL
1,2,BAJFINANCE,6073.536,7.913249,7672.010722,514.181356,6.61,High Risk,SELL
2,3,HINDUNILVR,4418.928,2.342267,5183.738846,472.456282,0.96,High Risk,SELL
7,8,BAJAJHLDNG,228.932,1.385717,218.838203,37.348250,-28.22,Value,SELL
8,9,CHOLAFIN,1383.684,12.022313,2478.949967,-62.056082,8.15,Value,SELL

In [11]:
sell.to_csv(
    OUTPUT / "sell_recommendations.csv",
    index=False
)

print("SELL recommendations saved!")

SELL recommendations saved!

In [12]:
top10 = analytics.sort_values(
    by="overall_score",
    ascending=False
).head(10)

top10

,rank,company_id,Performance_Score,growth_score,risk_score,overall_score,value_at_risk,investment_category,recommendation
0,1,COALINDIA,14427.668,-3.792529,10803.945328,3068.753483,-4.77,High Risk,SELL
1,2,BAJFINANCE,6073.536,7.913249,7672.010722,514.181356,6.61,High Risk,SELL
2,3,HINDUNILVR,4418.928,2.342267,5183.738846,472.456282,0.96,High Risk,SELL
3,4,BEL,1906.620,8.160364,2098.775705,240.810201,3.80,Value,HOLD
4,5,HEROMOTOCO,1635.056,6.623681,1747.970814,219.347985,-9.22,Value,BUY
5,6,CIPLA,1908.820,9.894390,2345.399098,180.641262,4.47,Value,HOLD
6,7,HAL,1570.432,5.636570,2261.626427,64.738993,2.89,Value,HOLD
7,8,BAJAJHLDNG,228.932,1.385717,218.838203,37.348250,-28.22,Value,SELL
8,9,CHOLAFIN,1383.684,12.022313,2478.949967,-62.056082,8.15,Value,SELL
9,10,ABB,189.988,4.281683,577.580626,-66.901367,2.30,Value,SELL

In [13]:
top10.to_csv(
    OUTPUT / "top10_recommendations.csv",
    index=False
)

print("Top 10 Recommendations Saved!")

Top 10 Recommendations Saved!

In [14]:
high_risk = analytics[
    analytics["risk_score"] >= 5000
].copy()

high_risk

,rank,company_id,Performance_Score,growth_score,risk_score,overall_score,value_at_risk,investment_category,recommendation
0,1,COALINDIA,14427.668,-3.792529,10803.945328,3068.753483,-4.77,High Risk,SELL
1,2,BAJFINANCE,6073.536,7.913249,7672.010722,514.181356,6.61,High Risk,SELL
2,3,HINDUNILVR,4418.928,2.342267,5183.738846,472.456282,0.96,High Risk,SELL
11,12,INDIGO,5319.928,-5.855329,8950.814263,-111.781731,-20.53,High Risk,SELL
48,49,INDUSINDBK,933.600,-0.853658,5628.239135,-1033.918564,3.79,High Risk,SELL
54,55,LTIM,61.060,1.719504,5117.616834,-1254.378382,3.03,High Risk,SELL
55,56,TATAPOWER,13.992,2.477463,5221.891968,-1299.009080,-9.05,High Risk,SELL
56,57,ADANIPOWER,46.312,-12.222588,5356.802016,-1324.953610,-10.52,High Risk,SELL
57,58,TECHM,13.496,23.364670,5618.714689,-1391.102638,-0.58,High Risk,SELL
58,59,JINDALSTEL,28.764,-6.209242,5611.372476,-1393.510754,-13.51,High Risk,SELL
59,60,ITC,27.040,2.559972,5785.941654,-1434.773423,-0.16,High Risk,SELL
60,61,AXISBANK,3616.232,6.582783,11654.917496,-1464.932600,2.04,High Risk,SELL
61,62,TITAN,29.588,-0.252814,6157.301960,-1527.578775,-0.86,High Risk,SELL
62,63,DMART,19.524,7.961571,7124.151482,-1770.441720,5.64,High Risk,SELL
63,64,WIPRO,0.000,4.521831,7291.626487,-1821.323981,-1.37,High Risk,SELL
64,65,ULTRACEMCO,82.952,-4.063967,7483.517034,-1839.120847,0.74,High Risk,SELL
65,66,BANKBARODA,1247.704,4.650827,11902.907564,-2475.017502,-4.21,High Risk,SELL
66,67,PNB,0.000,26.082059,10067.088594,-2507.643428,-6.10,High Risk,SELL
67,68,HINDALCO,7178.928,10.681676,21578.457140,-2519.304498,-7.19,High Risk,SELL
68,69,MOTHERSON,8.520,18.941943,10236.738569,-2549.146962,-4.91,High Risk,SELL
69,70,M&M,40.116,4.369179,10543.304441,-2618.250498,-14.50,High Risk,SELL
70,71,BHARTIARTL,23.644,26.041611,10762.613074,-2672.081104,-7.28,High Risk,SELL
71,72,ICICIPRULI,-543.808,0.140675,10003.514059,-2718.352479,-43.90,High Risk,SELL
72,73,PFC,39.564,5.605561,11229.474399,-2789.581053,0.57,High Risk,SELL
73,74,UNIONBANK,12.556,10.047002,11580.187819,-2886.508104,-0.48,High Risk,SELL
74,75,ADANIENT,15.412,35.438953,12061.888493,-2996.903690,-34.68,High Risk,SELL
75,76,HDFCLIFE,165.692,4.116590,12380.760242,-3027.472454,-28.42,High Risk,SELL
76,77,HCLTECH,33.204,5.464326,12420.545352,-3089.942224,-4.12,High Risk,SELL
77,78,KOTAKBANK,-3981.396,15.040469,6503.411427,-3213.147092,0.66,High Risk,SELL
78,79,MARUTI,138.900,2.526681,13536.071576,-3327.573556,-9.29,High Risk,SELL
79,80,GAIL,12.944,7.472754,14159.096805,-3531.981138,-17.12,High Risk,SELL
80,81,CANBK,-2311.712,6.250157,11253.311745,-3735.825181,-2.79,High Risk,SELL
81,82,BAJAJFINSV,36.740,8.127479,15510.622213,-3860.114936,-5.04,High Risk,SELL
82,83,GRASIM,36.280,-3.094256,15850.504001,-3949.196990,-4.38,High Risk,SELL
83,84,INFY,38.016,3.837492,16438.038157,-4092.960017,3.60,High Risk,SELL
84,85,SBILIFE,10.780,10.338335,16450.359375,-4104.659426,-9.39,High Risk,SELL
85,86,VEDL,0.000,44.248940,16605.570728,-4135.905553,-10.31,High Risk,SELL
86,87,NTPC,20.308,3.932629,16865.995026,-4206.999136,-2.98,High Risk,SELL
87,88,LT,63.768,4.765709,20344.966815,-5059.066506,1.23,High Risk,SELL
88,89,TATASTEEL,-0.332,-62.010647,20251.881829,-5084.806984,-18.34,High Risk,SELL
89,90,JSWSTEEL,20.220,-26.317270,20775.948340,-5195.110129,-17.12,High Risk,SELL
90,91,ICICIBANK,-4219.504,10.773719,17029.600994,-5941.431047,2.43,High Risk,SELL
91,92,TCS,66.576,4.380318,24523.675128,-6102.755271,4.49,High Risk,SELL
92,93,TATAMOTORS,47.384,2.721314,29419.138076,-7334.878459,-8.47,High Risk,SELL
93,94,SBIN,0.000,5.600772,36821.164947,-9203.330967,1.40,High Risk,SELL
94,95,BPCL,35.804,-19.768087,39132.870186,-9775.814777,-20.68,High Risk,SELL
95,96,LICI,40.780,2.910423,46467.687067,-11599.591119,5.03,High Risk,SELL
96,97,HDFCBANK,-13374.564,10.506897,36104.989240,-14372.395496,5.50,High Risk,SELL
97,98,IOC,21.412,-30.655940,66711.453583,-16680.028175,-23.80,High Risk,SELL
98,99,ONGC,23.576,-5.802478,74739.462815,-18677.466171,-23.14,High Risk,SELL
99,100,RELIANCE,24.684,2.281345,92496.651887,-23113.490901,-24.25,High Risk,SELL

In [15]:
high_risk.to_csv(
    OUTPUT / "high_risk_alerts.csv",
    index=False
)

print("High Risk Alerts Saved!")

High Risk Alerts Saved!

In [16]:
recommendation_dataset = analytics.copy()

recommendation_dataset.to_csv(
    OUTPUT / "recommendation_dataset.csv",
    index=False
)

print("Recommendation Dataset Saved Successfully!")

Recommendation Dataset Saved Successfully!